### PR TITLE
feat: support Xcode 15

### PR DESCRIPTION
**Pull request by hansemannn**

### CODE REVIEW

**Comment by cb1kenobi** [comment]
I did some research and found the sim runtimes are now installed as "disk images" in `/Library/Developer/CoreSimulator/Images` and mounted in `/Library/Developer/CoreSimulator/Volumes`. Once mounted, Node.js can read files in the mounted volume. The volumes are read only.

I have verified that `xcrun simctl list --json` will return the runtimes, but I haven't tested this code.

According to https://developer.apple.com/support/xcode/, Xcode 15 supports iOS 17, so we technically don't have to worry about mixing the older sim runtimes with the output from simctl.

FYI, if you unmount the sim runtime image, Xcode does not recover well and I had to delete and redownload/reinstall the runtime. Boo.

While I'm fine with switching to simctl to get the runtimes, I think `ioslib@3` will still need to scan the directories. `ioslib@3` is still lacking all the simulator start and simulator/device installing. I really need a Mac if I'm going to invest time into `ioslib@3`.

Stay tuned, will test as soon as I can.

**Comment by hansemannn** [comment]
Very thoughtful feedback, as usual, thank you Chris! Do you think, for Titanium right now, we should go with the solution provided in this branch?

**Comment by hansemannn** [comment]
@cb1kenobi What do we do with this one? :)

**Review by cb1kenobi — APPROVED** [review]
TESTED and APPROVED! Thank you!

**Comment by m1ga** [comment]
**quick info:**

`replaceAll` is only available starting in [node 15](https://tekloon.medium.com/how-to-fix-replaceall-is-not-a-function-in-node-js-caf459e00abf). During a user test (see [slack](https://tidev.slack.com/archives/C03CVQX2A/p1692648577627949)) it was producing error. Since we still support node 14 (or not explicitly exclude it) with the current SDK we should use a normal regex instead. 

A PR is currently in the making!

**Comment by cb1kenobi** [comment]
Bah, did this PR introduce a regression?

**Comment by m1ga** [comment]
yes, users that currently use node 14 won't be able to build apps with 12.2.0 for iOS.

**Pull request merged**
